### ISSUE TITLE
Some Timing Issues with the syllabus

### ISSUE THREAD

**Issue by chendaniely** [bi-sdal/workshop#1]
@dads2busy 
On the morning of May 23, the current syllabus says Unix and Git will be covered before lunch.
Assuming we start at 9, and lunch is at 12. I won't have enough time to cover the topics currently listed.
The Git stuff alone is about 3-3.5 hours of material.

We can move Git down to the next day (May 24), and move in project templates and data ingestion to the morning of the 23rd?

**Comment by dads2busy** [comment]
I think that switch will work

**Comment by chendaniely** [comment]
closing issue. git will be all day on the 23rd, and project templates will be throw in the mix
