### ISSUE TITLE
RJava & XLSX Installation on 

### ISSUE THREAD

**Issue by inrazhtet** [bi-sdal/workshop#4]
Hey @chendaniely ,

Lata and I are still having difficulties installing xlsx on our lightfoot server. 
This is the error we get. Could you take a look into it?

 Thanks!

`
If you do not have root privileges, run
R CMD javareconf -e
to set all Java-related variables and then install rJava.
ERROR: configuration failed for package ‘rJava’
* removing ‘/home/zarni90/R/x86_64-pc-linux-gnu-library/3.3/rJava’
`

**Comment by dads2busy** [comment]
Use rio . Works now

**Comment by inrazhtet** [comment]
@dads2busy thanks! Rio works!
